# Generated by Django 4.0.3 on 2022-05-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_airplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airplane_name', models.CharField(default='Airplane', max_length=30)),
                ('Airplane_type', models.CharField(max_length=30)),
                ('FirstFlightDate', models.DateField()),
                ('LastFlightDate', models.DateField()),
                ('FirstMaintenanceDate', models.DateField()),
                ('LastMaintenanceDate', models.DateField()),
            ],
        ),
    ]
