# Generated by Django 4.0.3 on 2022-05-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='on_maintenance',
            field=models.CharField(choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1),
        ),
    ]
