# Generated by Django 4.0.3 on 2022-05-07 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_location', models.CharField(max_length=100)),
                ('Cabin', models.CharField(max_length=100)),
                ('Seat_Number', models.CharField(max_length=100)),
                ('Date_of_Issue', models.DateField(default=datetime.datetime.today)),
                ('Flight_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flight')),
            ],
        ),
    ]
