# Generated by Django 4.0.3 on 2022-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_waitlist_person_booked_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateField(),
        ),
    ]
