# Generated by Django 4.0.3 on 2022-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_flight_time_alter_flight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Time',
            field=models.TimeField(default=''),
        ),
    ]
