# Generated by Django 4.0.3 on 2022-05-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_flight_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Time',
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Duration',
            field=models.CharField(max_length=30),
        ),
    ]
