# Generated by Django 4.0.3 on 2022-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_flight_time_alter_flight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateField(),
        ),
    ]
