# Generated by Django 4.0.3 on 2022-05-14 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_flight_flight_time_alter_flight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='User',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
